version: "3"

services:
# https://hub.docker.com/r/openfrontier/gerrit/
  gerrit:
    image: openfrontier/gerrit:2.13.8
    ports:
      - 8080
      - 29418:29418
    environment:
      - WEBURL=http://gerrit
      - DATABASE_TYPE=postgresql
      - DB_PORT_5432_TCP_ADDR=db
      - DB_PORT_5432_TCP_PORT=5432
      - DB_ENV_POSTGRES_DB=reviewdb
      - DB_ENV_POSTGRES_USER=gerrit2
      - DB_ENV_POSTGRES_PASSWORD=gerrit
#      - GERRIT_INIT_ARGS='--install-all-plugins'
      - AUTH_TYPE=DEVELOPMENT_BECOME_ANY_ACCOUNT
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:gerrit
        - traefik.port=8080
        - traefik.docker.network=gerrit_default
# TODO
#    secrets:
#    volumes:
#      - $HOME/gerrit_volume:/var/gerrit/review_site

# https://hub.docker.com/_/traefik/
  proxy:
    image: traefik:v1.3.0-alpine
    command: --web --docker --docker.swarmmode --docker.watch --docker.domain=gerrit --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    deploy:
      labels:
        - traefik.docker.network=gerrit_default
      placement:
        constraints:
          - node.role == manager

#https://github.com/dockersamples/docker-swarm-visualizer
  visualizer:
    image: dockersamples/visualizer
    ports:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - traefik.port=8080
        - traefik.frontend.rule=Host:visualizer.gerrit
        - traefik.docker.network=gerrit_default
      placement:
        constraints:
          - node.role == manager

# https://hub.docker.com/_/postgres/
# TODO - volumes and security
  db:
    image: postgres:9.6.3-alpine
    environment:
      - POSTGRES_DB=reviewdb      
      - POSTGRES_USER=gerrit2
      - POSTGRES_PASSWORD=gerrit
